### ISSUE TITLE
Liquibase-neo4j installation

### ISSUE THREAD

**Issue by OOub** [liquibase/liquibase-neo4j#147]
Hello, 

I'm trying to use this plugin and I followed the installation instructions (with the given examples) but I keep getting this error whenever I run updateSQL:

`Unexpected error running Liquibase: java.lang.RuntimeException: Cannot find database driver: org.neo4j.jdbc.bolt.BoltDriver`

I'm building the jar as follows:

```
# install liquibase-neo4j plugin
mkdir tmp
wget https://github.com/liquibase/liquibase-neo4j/archive/refs/tags/liquibase-neo4j-4.8.0.tar.gz
tar --extract --file liquibase-neo4j-*.tar.gz --directory tmp --strip-components=1
rm liquibase-neo4j-4.8.0.tar.gz
mvn package -f tmp -DskipTests
cp tmp/target/liquibase-neo4j-*-full.jar $LIQUIBASE_HOME/lib
```

Thanks,

**Comment by fbiville** [comment]
@OOub what you were trying was slightly different, since `https://github.com/liquibase/liquibase-neo4j/archive/refs/tags/liquibase-neo4j-4.8.0.tar.gz` are the archive for the **source** code, not the resulting full JAR.
I have fixed the configuration so that the "full" JAR is properly produced and clarified the instructions on how to download it.
