### ISSUE TITLE
 Cannot cast 'java.time.ZonedDateTime' to 'java.sql.Timestamp'

### ISSUE THREAD

**Issue by fanat12k** [liquibase/liquibase-neo4j#590]
We are trying to update to the last version liquibase from 4.18.0 to 4.27.0 
and we encountered this problem after the update: 

How you see it in the screenshot - Cannot cast 'java.time.ZonedDateTime' to 'java.sql.Timestamp'

<img width="1706" alt="1" src="https://github.com/liquibase/liquibase-neo4j/assets/16311077/fecd6b35-5400-4144-954e-33f5d6fdf0d8">

But when you change the type to ZonedDateTime, everything works as it should; by default, the function datetime() in neo4j returns ZonedDateTime. Any ideas?

<img width="1587" alt="2" src="https://github.com/liquibase/liquibase-neo4j/assets/16311077/4394ba06-8d9c-4505-9724-c40ecabb86b1">

**Comment by fbiville** [comment]
Hello, thanks for the report.
This seems to be exactly the same as https://github.com/liquibase/liquibase-neo4j/issues/314.
The [following documentation section](https://www.neo4j.com/labs/liquibase/docs/reference-configuration/#jdbc-connectivity) explains how to configure the JDBC connector so that this particular conversion issue goes away.
Does that help?

**Comment by fanat12k** [comment]
<img width="730" alt="Знімок екрана 2024-04-03 о 14 20 07" src="https://github.com/liquibase/liquibase-neo4j/assets/16311077/6ca6872a-1a96-4d58-96d9-66dee54140a9">

**Comment by fbiville** [comment]
Thanks, the `driverClassName` needs to change to `liquibase.ext.neo4j.database.jdbc.Neo4jDriver`.

**Comment by fanat12k** [comment]
Thank you it helped

**Comment by fbiville** [comment]
Closing this for now, feel free to reopen the issue if you need a follow-up.
